config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :categories, :only => [:show] do
    resources :pages, :only => [:index, :show]
  end

  namespace :admin do
    get 'base/index'
    root 'base#index'

    resources :settings, :only => [:index, :create, :update, :destroy] do
      member do
        post :sort
        post :update_link
      end
    end
    resources :users
    resources :categories do
      collection do
        get :manage
        post :rebuild
      end
      resources :pages
    end
  end

end

app/views/admin/pages/_news_form.html.erb
<%= form_for [:admin, @category, @page] do |f| %>

  <div class="form-control-static">
    <%= f.text_field :title, :placeholder => "新闻标题", :class => "form-control" %>
  </div>

  <%= f.kindeditor :content %>

  <div class="form-control-static">
    <%= f.submit "保存", :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/admin/pages/_products_form.html.erb
<%= form_for [:admin, @category, @page] do |f| %>

  <div class="form-control-static">
    <%= f.text_field :title, :placeholder => "标题", :class => "form-control" %>
  </div>

  <div class="form-control-static form-control margin-bottom-10">
    <%= f.file_field :photo, :placeholder => "上传产品图片" %>
  </div>

  <%= f.kindeditor :content %>

  <div class="form-control-static">
    <%= f.submit "保存", :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/admin/pages/_products_list.html.erb
<table class="table table-hover table-condensed table-bordered">
  <thead>
    <tr>
      <th><%= sort_link(@q, :id, "ID") %></th>
      <th><%= sort_link(@q, :title, "标题") %></th>
      <th>图片</th>
      <th><%= sort_link(@q, :created_at, "创建时间") %></th>
      <th><%= link_to "新建产品", new_admin_category_page_path(@category), :class => "btn btn-success" %></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.id %></td>
        <td><%= link_to page.title, admin_category_page_path(@category, page) %></td>
        <td><%= image_tag page.photo_url(:mini) if page.photo.present? %></td>
        <td><%= short_datetime page.created_at %></td>
        <td>
          <%= link_to edit_admin_category_page_path(@category, page) do %>
            <i class="fa fa-edit"></i> 修改产品
          <% end %>
          <%= link_to admin_category_page_path(@category, page), :method => :delete, :class => 'delete', :'data-confirm' => "确定要删除？" do %>
            <i class="fa fa-times"></i> 删除产品
          <% end %>
        </td>
      </tr>
    <% end %>
    <% if @pages.blank? %>
      <tr>
        <td colspan='5' class="not_found">未找到</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/pages/_tab.html.erb
<ul class="nav nav-tabs margin-bottom-10">
  <% if @action == :new %>
    <li role="presentation" class="active"><%= link_to "编辑", "javascript:;" %></li>
  <% else %>
    <li role="presentation" class="<%= is_active?(:show) %>"><%= link_to "预览", tab_link_path(:show) %></li>
    <li role="presentation" class="<%= is_active?(:edit) %>"><%= link_to "编辑", tab_link_path(:edit) %></li>
  <% end %>
</ul>

app/views/admin/pages/index.html.erb
<% breadcrumb :show_category, @category %>

<div class="page-header">
  <h3><%= @category.name %></h3>
</div>

<div class="well well-sm">
  <%= search_form_for [:admin, @category, @q], :class => "form-inline" do |f| %>

    <div class="form-group">
      <%= f.label :id_eq, "ID" %>
      <%= f.search_field :id_eq, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :title_cont, "标题" %>
      <%= f.search_field :title_cont, :class => "form-control" %>
    </div>

    <%= f.submit "搜索", :class => "btn btn-primary" %>
  <% end %>
</div>

<div>
  <%= render "#{@category.type_name}_list" %>
  <%= paginate @pages %>
</div>

app/views/admin/pages/information_edit.html.erb
<% breadcrumb :show_category, @category %>

<div class="page-header">
  <h3><%= @category.name %></h3>
</div>

<%= render 'tab' %>

<%= form_for [:admin, @category, @page] do |f| %>

  <%= f.kindeditor :content %>

  <div class="form-control-static">
    <%= f.submit "保存", :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/admin/pages/information_show.html.erb
<% breadcrumb :show_category, @category %>

<div class="page-header">
  <h3><%= @category.name %></h3>
</div>

<%= render 'tab' %>

<%= render "/pages/#{@category.type_name}_show" %>

app/views/admin/pages/news_edit.html.erb
<% breadcrumb :page, @page %>

<div class="page-header">
  <h3><%= @category.name %></h3>
</div>

<%= render 'tab' %>

<%= render 'news_form' %>

app/views/admin/pages/news_new.html.erb
<% breadcrumb :page, @page %>

<div class="page-header">
  <h3><%= @category.name %></h3>
</div>

<%= render 'tab' %>

<%= render 'news_form' %>

app/views/admin/pages/news_show.html.erb
<% breadcrumb :page, @page %>

<div class="page-header">
  <h3><%= @category.name %></h3>
</div>

<%= render 'tab' %>

<%= render "/pages/#{@category.type_name}_show" %>

app/views/admin/pages/products_edit.html.erb
<% breadcrumb :page, @page %>

<div class="page-header">
  <h3><%= @category.name %></h3>
</div>

<%= render 'tab' %>

<%= render 'products_form' %>

app/views/admin/pages/products_new.html.erb
<% breadcrumb :page, @page %>

<div class="page-header">
  <h3><%= @category.name %></h3>
</div>

<%= render 'tab' %>

<%= render 'products_form' %>

app/views/admin/pages/products_show.html.erb
<% breadcrumb :page, @page %>

<div class="page-header">
  <h3><%= @category.name %></h3>
</div>

<%= render 'tab' %>

<%= render "/pages/#{@category.type_name}_show" %>

app/views/admin/pages/site_map_edit.html.erb
<% breadcrumb :show_category, @category %>

<div class="page-header">
  <h3><%= @category.name %></h3>
</div>

<%= render 'tab' %>


<p>网站地图由程序自动生成，不可编辑。</p>