config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :categories, :only => [:show] do
    resources :pages, :only => [:index, :show]
  end

  namespace :admin do
    get 'base/index'
    root 'base#index'

    resources :settings, :only => [:index, :create, :update, :destroy] do
      member do
        post :sort
        post :update_link
      end
    end
    resources :users
    resources :categories do
      collection do
        get :manage
        post :rebuild
      end
      resources :pages
    end
  end

end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "后台管理", admin_root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "返回前台", root_path %></li>
        <li class="dropdown">
          <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.login %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "修改资料", edit_admin_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "退出", session_path(current_user), :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin/_iefix.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/admin/_sidebar.html.erb
<ul class="nav nav-sidebar">
  <li><%= link_to "首页", admin_root_path %></li>
  <li><%= link_to "网站设置", admin_settings_path %></li>
  <li><%= link_to "用户管理", admin_users_path %></li>
  <li><%= link_to "网站结构", manage_admin_categories_path %></li>
  <% @roots.each do |root| %>
    <li><%= link_to root.name, admin_category_path(root) %></li>
  <% end %>
</ul>