config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :categories, :only => [:show] do
    resources :pages, :only => [:index, :show]
  end

  namespace :admin do
    get 'base/index'
    root 'base#index'

    resources :settings, :only => [:index, :create, :update, :destroy] do
      member do
        post :sort
        post :update_link
      end
    end
    resources :users
    resources :categories do
      collection do
        get :manage
        post :rebuild
      end
      resources :pages
    end
  end

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController

  before_filter :get_index_images, :only => [:index, :create]

  def index
    
  end

  def create
    @index_image = IndexImage.new(index_image_params)
    if @index_image.save
      redirect_to admin_settings_path
    else
      render :index
    end
  end

  def update
    logo_file = params[:settings].delete(:site_logo_file)
    Settings.update_settings(params[:settings])

    if logo_file.present?
      uploader = LogoPhotoUploader.new
      uploader.store!(logo_file)
      Settings.site_logo = "/uploads/logo/logo." + logo_file.original_filename.split(".").last
      Settings.save!
    end

    redirect_to admin_settings_path
  end

  def destroy
    @index_image = IndexImage.find(params[:id])
    @index_image.destroy
    redirect_to admin_settings_path
  end

  def sort
    @index_image = IndexImage.find(params[:id])
    @index_image.insert_at params[:position].to_i
    return render :text => "ok"
  end

  def update_link
    @index_image = IndexImage.find(params[:id])
    @index_image.update_attributes(edit_index_image_params)
    return render :js => "
      $('#index_#{@index_image.id} .index_image_link a').text('#{@index_image.link}');
      $('#edit_index_image button.close').click();
    "
  end

  protected

  def get_index_images
    @index_images = IndexImage.all
    @index_image = IndexImage.new
  end

  def index_image_params
    params.require(:index_image).permit(:photo, :link)
  end

  def edit_index_image_params
    params.require(:index_image).permit(:link)
  end

end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/views/admin/settings/_index_images.html.erb
<h3>首页滚动图片</h3>
<table class="table table-hover table-condensed table-bordered">
  <thead>
    <tr>
      <td>ID</td>
      <td>缩略图</td>
      <td>链接</td>
      <td></td>
    </tr>
  </thead>
  <tbody id="index_images_list">
    <% @index_images.each do |image| %>
      <tr id="index_<%= image.id %>">
        <td><%= image.position %></td>
        <td class="index_image_photo"><%= image_tag image.photo_url(:thumb) if image.photo_url %></td>
        <td class="index_image_link"><%= link_to image.link, image.link %></td>
        <td>
          <%= link_to "javascript:;", :data => {:toggle => "modal", :target => "#edit_index_image", :id => image.id} do %>
            <i class="fa fa-edit"></i> 修改链接
          <% end %>
          <%= link_to admin_setting_path(image), :method => :delete, :class => 'delete', :'data-confirm' => "确定要删除？" do %>
            <i class="fa fa-times"></i> 删除
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= simple_form_for [:admin, @index_image], :url => admin_settings_path, :method => :post do |f| %>
  <table class="table table-hover table-condensed table-bordered">
    <tr>
      <td><%= f.input :photo, :as => :file %></td>
      <td><%= f.input :link %></td>
      <td><%= f.button :submit, :value => "新建" %></td>
    </tr>
  </table>
<% end %>

<div class="modal fade" id="edit_index_image" tabindex="-1" role="dialog" aria-labelledby="edit_label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="edit_label">编辑链接</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [:admin, @index_image], :url => update_link_admin_setting_path(0), :method => :post, :remote => true do |f| %>
          <table class="table table-hover table-condensed table-bordered">
            <tr>
              <td>缩略图</td>
              <td id="modal_photo"></td>
            </tr>
            <tr>
              <td>链接</td>
              <td><%= f.text_field :link, :id => "modal_link" %></td>
            </tr>
          </table>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
        <button type="button" class="btn btn-primary" id="modal_submit">保存</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/settings/_page_footer.html.erb
<h3>页脚</h3>
<%= simple_form_for [:admin, Settings], :as => :settings, :url => admin_setting_path(0), :method => :put, :html => {:class => "form-horizontal"} do |f| %>
  <%= f.input :copy_right %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>
<% end %>

app/views/admin/settings/_page_header.html.erb
<h3>页头</h3>
<%= simple_form_for [:admin, Settings], :as => :settings, :url => admin_setting_path(0), :method => :put, :html => {:class => "form-horizontal"} do |f| %>
  <%= f.input :site_name %>
  <%= f.input :site_logo_file, :as => :file %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>
<% end %>

app/views/admin/settings/_seo.html.erb
<h3>搜索引擎</h3>
<%= simple_form_for [:admin, Settings], :as => :settings, :url => admin_setting_path(0), :method => :put, :html => {:class => "form-horizontal"} do |f| %>

  <%= f.input :site_description %>
  <%= f.input :site_keywords %>
  <%= f.input :baidu_validate_meta %>
  <%= f.input :site_search_js, :as => :text %>
  <%= f.input :baidu_js, :as => :text %>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :value => "保存" %>
    </div>
  </div>
<% end %>

app/views/admin/settings/index.html.erb
<% breadcrumb :settings %>

<div class="page-header">
  <h3>网站设置</h3>
</div>

<%= render 'page_header' %>
<%= render 'index_images' %>
<%= render 'page_footer' %>
<%= render 'seo' %>